config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  get 'tags/index'
  resources :categories
  resources :tags
  get 'home/read/:id', to: 'home#read', :as => :post_read
  get 'home/:tag/posts', to: 'home#tag_search', :as => :tag_search
  get 'category/index'
  get 'category/show'
  get 'home/posts/:category', to: 'home#category_search_post', :as => :category_search_post
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root 'home#index'
get 'home/ok'
get 'home/index'
get 'home/about', as: :about
get 'home/contact', as: :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true
    has_many :posts, dependent: :nullify #:destroy
    before_save :create_slug

    def create_slug
        self.slug=self.name.downcase.tr(" ","-")
    end

end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :category
    belongs_to :user
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings
    default_scope {order :created_at}
    scope :published, -> { where(published:true) }
    scope :unpublished, -> { where.not(published:true) }
    scope :order_by_latest, -> { reorder(created_at: :desc) }
    has_rich_text :Body
    def all_tags=(tag_names)
        if tag_names.blank?
            return
        end
        self.tags=tag_names.split(",").map do |tag_name|
            unless tag_name.blank?
                Tag.where(name: tag_name.strip).first_or_create!
            end
        end
    end
    
    def all_tags
        tags.map(&:name).join(",")
    end


end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :name, presence: true
    has_many :taggings
    has_many :posts, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description, :published, :slug)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def ok
        render plain: "OK"
    end

    def index
        @categories = Category.all.includes(:posts)
        @tags = Tag.includes(:posts)
        @posts = Post.includes(:tags).order_by_latest.published
        #render plain: "This is an index page."
    end

    def tag_search

        if params.has_key? (:tag)
          # @posts = Tag.find_by(:name => params[:tag]).posts
          
          result = Tag.where(name: params[:tag])
          @posts = result.blank? ? [] : result.first.posts
    
        end
    
        render "home/index"
    end

    def category_search_post

        if params.has_key? (:category)
        @posts = Category.find_by(:slug=> params[:category]).posts
    
        end
    
        render "home/index"
    end

    def read
        @post=Post.find(params[:id])
    end
    def about
        #render plain:"This is a about page"
    end

    def contact
        #render plain:"This is a contact page"
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :check_authorization?, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.includes(:category).order("created_at DESC")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:Title, :Body, :Published, :category_id, :all_tags,tag_ids:[])
    end

    def check_authorization?
      unless authorize?(@post)
        flash[:notice]="Unauthorize Access"
        redirect_back(fallback_location: root_url)
      end
    end


    def authorize?(post)
      current_user.id==post.user.id
    end
    
    helper_method :authorize?
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :destroy, :edit, :update]
  #before_action 
  def index
    @tags=Tag.all
  end
  def show
    @tag=Tag.find(params[:id])
  end
  def new
    @tag= Tag.new
  end

  def edit
  end



  def update
    if @tag.update(tag_params)
      redirect_to tags_path, notice: "Tag was successfully updated."
    else
      render :edit
    end
  end

  def create
    p params
    @tag= Tag.new(tag_params)
    if @tag.save
    redirect_to tags_path, notice: "Tag was successfully created."
    else
      render :new
    end

  end
  def destroy
    @tag=Tag.find(params[:id])
    @tag.destroy
    redirect_to tags_path, notice: "Tag was successfully deleted."
  end
  private
  def set_tag 
    @tag = Tag.find(params[:id])
  end
  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :published %>
    <%= form.check_box :published %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>
<%= link_to 'New Category', new_category_path, class: "btn btn-success" %>
<table class= "table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= category.published %></td>
        <td><%= link_to 'Show', category, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_category_path(category), class: "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<p>
  <strong>Published:</strong>
  <%= @category.published %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/about.html.erb
<h1>This is a about page</h1>
<%= @check %>

app/views/home/contact.html.erb
<h1><a href="https://github.com/RajatTiwari30/RubyPractices">GIT HUB LINK</a></h1>

app/views/home/index.html.erb
<h1>Welcome to Rails Blog</h1>
<% @posts.each do |post| %>
<div class='card mb-3'>
    <div class='card body'>
    <h4><%= post.Title %></h4>
    <div class= "d-flex justify-content-between">
    <span class="badge badge-light"><%= link_to post.category.name, category_search_post_path(post.category.slug) %></span>
    </div>
        <div><%= post.Body.to_plain_text[0..200] %>
        </div>
    </div>
    <div class='card footer'>
    <h6>Published: <%= time_ago_in_words(post.created_at) %> ago.</h6>
    <h6>Author: <%= post.user.email %></h6>
    <div class= "d-flex justify-content-start">
    <% post.tags.each do |tag|%>
    <span class="badge badge-warning mr-2"><%= link_to tag.name, tag_search_path(tag.name) %></span>
    <% end %>
    </div>
    <%= link_to "read more", post_read_path(post) %>
    </div>
</div>
<% end %>

app/views/home/read.html.erb
<div class="container">
    <div class= "d-flex justify-content-between align-items-center">
    <h2><%= @post.Title %></h2>
    <span class='badge badge-info'><%= @post.category.name %></span>
    </div>
    <div>
        <%= @post.Body %>
    </div>
    <%= link_to 'back', root_url%>
</div>

app/views/layouts/_categories.html.erb
<ul>
<% categories.each do |category| %>
    <li><%= link_to_if category.posts.size>0, category.name, category_search_post_path(category.slug) %></li> (<%= category.posts.size %>)
<% end %>
</ul>

app/views/layouts/_posts.html.erb
<ul>
<% posts.each do |post| %>
    <li><%= post.Title %></li>
<% end %>
</ul>

app/views/layouts/_tags.html.erb
<ul>
<% tags.each do |tag| %>
    <li><%= link_to_if tag.posts.size>0, tag.name, tag_search_path(tag.name) %></li>(<%= tag.posts.size %>)
<% end %>
</ul>

app/views/layouts/_topmenu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Home", root_url, class: "navbar-brand"  %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      
      <%= link_to "Categories", categories_path, class: "nav-link"  %>
      <%= link_to "Tags", tags_path,class: "nav-link"  %>
      <%= link_to "Posts", posts_path,class: "nav-link" %>
      <%= link_to "About", about_path,class: "nav-link" %>
      <%= link_to "Contact", contact_path,class: "nav-link" %>
    </div>
  </div>
        <div class="d-flex align-items-center justify-content-end">
        <% if user_signed_in? %>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        <% else %>
        <%= link_to "Sign In", new_user_session_path%>|
        <%= link_to "Sign Up", new_user_registration_path%>
        <%end %>
        </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class= "container">
      <%= render partial:"layouts/topmenu"%>
        <p class="notice"><%= notice %></p>
         <p class="alert"><%= alert %></p>

        <div class="row">
          <div class= "col-md-9">
            <%= yield %>
          </div>
          <div class="col-md-3">
            <% if @categories %>
            <h6>CATEGORIES</h6>
            <%= render 'layouts/categories', categories: @categories %>
            <% end %>
            <% if @tags %>
            <h6>TAGS</h6>
            <%= render 'layouts/tags', tags: @tags %>
            <% end %>
          </div>
        </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Title %>
    <%= form.text_field :Title %>
  </div>

  <div class="field">
    <%= form.label :tag %>
    <%= form.collection_check_boxes :tag_ids, Tag.all, :id, :name,
    {include_blank: true}%>
  </div>

  <div class="field">
    <%= form.label :new_tags %>
    <%= form.text_field :all_tags, placeholder: "Enter tags separated by comma" %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.collection_select :category_id, Category.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :Body %>
    <%= form.rich_text_area :Body %>
  </div>

  <div class="field">
    <%= form.label :Published %>
    <%= form.check_box :Published %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<%= link_to 'New Post', new_post_path, class: "btn btn-success" %>
<table class= "table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Author</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.Title %></td>
        <td><%= post.category.name %></td>
        <td><%= post.user.email %></td>
        <td><%= post.Published %></td>
        <td><%= link_to 'Show', post, class: "btn btn-primary" %></td>
        <% if authorize?(post)%>
          <td><%= link_to 'Edit', edit_post_path(post), class: "btn btn-primary" %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.Title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.Body %>
</p>

<p>
  <strong>Published:</strong>
  <%= @post.Published %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/tags/edit.html.erb
<h1>UPDATE TAG</h1>

<%= form_with(model: @tag, local: true) do |form| %>
    <% if @tag.errors.any? %>
        <div id="error">
            <h2>
            <%= pluralize(@tag.errors.count, "error") %> occured !
            </h2>
            <ul>
                <% @tag.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
    </div>
    <%= form.submit %>
    <%end%>
    <%= link_to "Back", tags_path %>

app/views/tags/index.html.erb
<h2>ALL TAGS</h2>
<%= link_to 'New Tag', new_tag_path, class: "btn btn-success"%>
<table class= "table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag), class: "btn btn-primary" %></td>
        <td><%= link_to 'Delete', tag, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tags/new.html.erb
<h1>NEW TAG</h1>

<%= form_with(model: @tag, local: true) do |form| %>
    <% if @tag.errors.any? %>
        <div id="error">
            <h2>
            <%= pluralize(@tag.errors.count, "error") %> occured !
            </h2>
            <ul>
                <% @tag.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
    </div>
    <%= form.submit %>
    <%end%>
    <%= link_to "Back", tags_path %>

app/views/tags/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>
<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>